---
title: "Homework-15.qmd"
author: "ML"
format: html
editor: visual
---

## Homework 15

Working through chapter 3 of Getting Started with R

```{r}
#setting things up
rm(list = ls()) #clears environment
library (tidyverse)
library (here)
```

read in compensation data and try out functions

```{r}
compensation <- read.csv (here("data", "compensation.csv"))
summary (compensation)
```

## dplyr verbs

subsetting

```{r}
names (compensation) # tells me names of columns
select (compensation, Fruit) # grabs columns
select (compensation, -Root) # all but one column
 
slice (compensation, 2) # grabs rows
slice (compensation, 2:10)
slice (compensation, c(2,3,10))

with (compensation, Fruit>80) # look within the data frame for Fruit >80
filter (compensation, Fruit>80) # returns pieces of the dataset according to the condition
filter (compensation, Fruit>80 | Fruit <20)

lo_hi_fruit <- filter (compensation, Fruit>80 | Fruit <20)
lo_hi_fruit
```

transforming

```{r}
head (compensation)
compensation <- mutate (compensation, logFruit = log(Fruit)) # makes a new column with designated transformation
head (compensation)
```

sorting

```{r}
arrange (compensation, Fruit)
```

mini-summary and two top tips

```{r}
select (filter (compensation, Fruit>80),Root)
# you can use more than 1 function at a time 


# %>% pipe - put the answer of the left hand command into the function on the right
compensation %>% # work with compensation data
  filter (Fruit>80) %>% # in fruit column, get all the rows that Fruit>80
    select(Root) # pass this data fram to return only the Root column
```

calculate summary statistics

```{r}
group_by()
mean ()
sd ()

# nested approach

summarise(
  group_by(compensation, Grazing), # makes grazing our grouping variable
  meanFruit = mean(Fruit) # mean calculated based on Fruit column
)

# pipe approach
compensation %>% # declare the data frame
  group_by (Grazing)%>% # divide into groups
    summarise (meanFruit = mean(Fruit)) # calculate the mean in each group

```

summarize and extend new summarization

```{r}
# multiple metrics at once
compensation %>% # declare the data frame
  group_by (Grazing) %>% # divide into groups
    summarise(
      meanFruit1 = mean(Fruit), sdFruit1 = sd(Fruit), medianFruit1 = median(Fruit))
```